# Generated by Django 4.2 on 2023-04-17 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
