# Generated by Django 4.2 on 2023-04-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('coursecode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('coursename', models.TextField(max_length=128)),
                ('cousedate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
