# Generated by Django 4.2 on 2023-04-17 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentcourse',
        ),
        migrations.AddField(
            model_name='student',
            name='coursecode',
            field=models.ForeignKey(default='UNKNOWN', on_delete=django.db.models.deletion.CASCADE, to='registration.course'),
        ),
    ]
