# Generated by Django 4.2 on 2023-05-08 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_student_studentcourse_student_coursecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='coursecode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.course'),
        ),
    ]
